# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768d656f7cc6165705b12001efc067bd51da7c9027c1185adc7892b589df195c2eccd8850d5bded1f834b9deaca341198ec7936fc26f21298c9300fb08a662f2

test:
  secret_key_base: 39dcabe57fbbbc521a00ec4a08d2bda320908c03a01e1fab9778558fe1cf35a4f49d46019828a357c967b86a03136fad51b79e01139ebd88ab1220934312de3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
